import type { StudentProfile, Semester } from './types';

const STUDENT_PROFILE: StudentProfile = {
  program: {
    id: 'bca',
    name: 'BCA',
    fullName: 'Bachelor of Computer Applications',
    totalYears: 3,
  },
  currentYear: 2,
  currentSemester: 1,
};

const SEMESTERS: Semester[] = [
  // Year 1 — Semester 1 (past)
  {
    year: 1,
    semester: 1,
    sgpa: 7.8,
    result: 'pass',
    subjects: [
      {
        id: 'y1s1-1',
        name: 'C Programming',
        code: 'BCA101',
        instructor: 'Dr. Priya Sharma',
        credits: 4,
        internal: 32,
        external: 45,
        total: 77,
        grade: 'A',
        attendancePercent: 88,
        syllabusPercent: 100,
        topics: [
          { name: 'Variables & Data Types', completed: true },
          { name: 'Control Structures', completed: true },
          { name: 'Functions', completed: true },
          { name: 'Arrays & Strings', completed: true },
          { name: 'Pointers', completed: true },
          { name: 'File Handling', completed: true },
        ],
      },
      {
        id: 'y1s1-2',
        name: 'Mathematics I',
        code: 'BCA102',
        instructor: 'Prof. Rakesh Mehta',
        credits: 4,
        internal: 28,
        external: 40,
        total: 68,
        grade: 'B+',
        attendancePercent: 82,
        syllabusPercent: 100,
        topics: [
          { name: 'Matrices & Determinants', completed: true },
          { name: 'Differential Calculus', completed: true },
          { name: 'Integral Calculus', completed: true },
          { name: 'Sequences & Series', completed: true },
          { name: 'Coordinate Geometry', completed: true },
        ],
      },
      {
        id: 'y1s1-3',
        name: 'English Communication',
        code: 'BCA103',
        instructor: 'Dr. Anita Desai',
        credits: 2,
        internal: 35,
        external: 52,
        total: 87,
        grade: 'A+',
        attendancePercent: 90,
        syllabusPercent: 100,
        topics: [
          { name: 'Grammar & Usage', completed: true },
          { name: 'Reading Comprehension', completed: true },
          { name: 'Essay Writing', completed: true },
          { name: 'Presentation Skills', completed: true },
        ],
      },
      {
        id: 'y1s1-4',
        name: 'Physics',
        code: 'BCA104',
        instructor: 'Prof. Vivek Kumar',
        credits: 3,
        internal: 30,
        external: 38,
        total: 68,
        grade: 'B+',
        attendancePercent: 76,
        syllabusPercent: 100,
        topics: [
          { name: 'Mechanics', completed: true },
          { name: 'Waves & Optics', completed: true },
          { name: 'Electricity & Magnetism', completed: true },
          { name: 'Semiconductor Physics', completed: true },
        ],
      },
      {
        id: 'y1s1-5',
        name: 'Digital Electronics',
        code: 'BCA105',
        instructor: 'Dr. Suresh Patil',
        credits: 4,
        internal: 34,
        external: 48,
        total: 82,
        grade: 'A',
        attendancePercent: 85,
        syllabusPercent: 100,
        topics: [
          { name: 'Number Systems', completed: true },
          { name: 'Logic Gates', completed: true },
          { name: 'Boolean Algebra', completed: true },
          { name: 'Combinational Circuits', completed: true },
          { name: 'Sequential Circuits', completed: true },
        ],
      },
      {
        id: 'y1s1-6',
        name: 'Environmental Studies',
        code: 'BCA106',
        instructor: 'Prof. Meena Joshi',
        credits: 2,
        internal: 30,
        external: 42,
        total: 72,
        grade: 'A',
        attendancePercent: 80,
        syllabusPercent: 100,
        topics: [
          { name: 'Ecosystems', completed: true },
          { name: 'Biodiversity', completed: true },
          { name: 'Pollution & Control', completed: true },
          { name: 'Sustainable Development', completed: true },
        ],
      },
    ],
  },
  // Year 1 — Semester 2 (past)
  {
    year: 1,
    semester: 2,
    sgpa: 8.2,
    result: 'pass',
    subjects: [
      {
        id: 'y1s2-1',
        name: 'Data Structures',
        code: 'BCA201',
        instructor: 'Dr. Priya Sharma',
        credits: 4,
        internal: 36,
        external: 50,
        total: 86,
        grade: 'A+',
        attendancePercent: 90,
        syllabusPercent: 100,
        topics: [
          { name: 'Arrays & Linked Lists', completed: true },
          { name: 'Stacks & Queues', completed: true },
          { name: 'Trees & BST', completed: true },
          { name: 'Graphs', completed: true },
          { name: 'Sorting Algorithms', completed: true },
          { name: 'Hashing', completed: true },
        ],
      },
      {
        id: 'y1s2-2',
        name: 'Mathematics II',
        code: 'BCA202',
        instructor: 'Prof. Rakesh Mehta',
        credits: 4,
        internal: 30,
        external: 44,
        total: 74,
        grade: 'A',
        attendancePercent: 84,
        syllabusPercent: 100,
        topics: [
          { name: 'Linear Algebra', completed: true },
          { name: 'Probability', completed: true },
          { name: 'Statistics', completed: true },
          { name: 'Numerical Methods', completed: true },
        ],
      },
      {
        id: 'y1s2-3',
        name: 'OOP with Java',
        code: 'BCA203',
        instructor: 'Dr. Kavita Rao',
        credits: 4,
        internal: 34,
        external: 48,
        total: 82,
        grade: 'A',
        attendancePercent: 86,
        syllabusPercent: 100,
        topics: [
          { name: 'Classes & Objects', completed: true },
          { name: 'Inheritance & Polymorphism', completed: true },
          { name: 'Interfaces & Packages', completed: true },
          { name: 'Exception Handling', completed: true },
          { name: 'Multithreading', completed: true },
        ],
      },
      {
        id: 'y1s2-4',
        name: 'Computer Organization',
        code: 'BCA204',
        instructor: 'Dr. Suresh Patil',
        credits: 3,
        internal: 28,
        external: 42,
        total: 70,
        grade: 'B+',
        attendancePercent: 78,
        syllabusPercent: 100,
        topics: [
          { name: 'CPU Architecture', completed: true },
          { name: 'Memory Organization', completed: true },
          { name: 'I/O Organization', completed: true },
          { name: 'Instruction Set Architecture', completed: true },
        ],
      },
      {
        id: 'y1s2-5',
        name: 'Financial Accounting',
        code: 'BCA205',
        instructor: 'Prof. Deepa Nair',
        credits: 3,
        internal: 32,
        external: 46,
        total: 78,
        grade: 'A',
        attendancePercent: 82,
        syllabusPercent: 100,
        topics: [
          { name: 'Accounting Principles', completed: true },
          { name: 'Journal & Ledger', completed: true },
          { name: 'Trial Balance', completed: true },
          { name: 'Financial Statements', completed: true },
        ],
      },
      {
        id: 'y1s2-6',
        name: 'Communication Skills',
        code: 'BCA206',
        instructor: 'Dr. Anita Desai',
        credits: 2,
        internal: 36,
        external: 50,
        total: 86,
        grade: 'A+',
        attendancePercent: 92,
        syllabusPercent: 100,
        topics: [
          { name: 'Business Writing', completed: true },
          { name: 'Group Discussion', completed: true },
          { name: 'Interview Skills', completed: true },
          { name: 'Public Speaking', completed: true },
        ],
      },
    ],
  },
  // Year 2 — Semester 1 (current)
  {
    year: 2,
    semester: 1,
    sgpa: 0,
    result: 'current',
    subjects: [
      {
        id: 'y2s1-1',
        name: 'Database Management Systems',
        code: 'BCA301',
        instructor: 'Prof. Rakesh Mehta',
        credits: 4,
        internal: 30,
        external: 0,
        total: 30,
        grade: '-',
        attendancePercent: 85,
        syllabusPercent: 72,
        topics: [
          { name: 'ER Modeling', completed: true },
          { name: 'Relational Algebra', completed: true },
          { name: 'SQL Fundamentals', completed: true },
          { name: 'Normalization', completed: true },
          { name: 'Transactions & Concurrency', completed: false },
          { name: 'Indexing & Hashing', completed: false },
        ],
      },
      {
        id: 'y2s1-2',
        name: 'Operating Systems',
        code: 'BCA302',
        instructor: 'Dr. Anita Desai',
        credits: 4,
        internal: 28,
        external: 0,
        total: 28,
        grade: '-',
        attendancePercent: 78,
        syllabusPercent: 60,
        topics: [
          { name: 'Process Management', completed: true },
          { name: 'CPU Scheduling', completed: true },
          { name: 'Memory Management', completed: true },
          { name: 'Virtual Memory', completed: false },
          { name: 'File Systems', completed: false },
          { name: 'I/O Systems', completed: false },
        ],
      },
      {
        id: 'y2s1-3',
        name: 'Computer Networks',
        code: 'BCA303',
        instructor: 'Prof. Vivek Kumar',
        credits: 4,
        internal: 32,
        external: 0,
        total: 32,
        grade: '-',
        attendancePercent: 88,
        syllabusPercent: 45,
        topics: [
          { name: 'OSI & TCP/IP Models', completed: true },
          { name: 'Data Link Layer', completed: true },
          { name: 'Network Layer & Routing', completed: false },
          { name: 'Transport Layer', completed: false },
          { name: 'Application Layer', completed: false },
          { name: 'Network Security', completed: false },
        ],
      },
      {
        id: 'y2s1-4',
        name: 'Web Technologies',
        code: 'BCA304',
        instructor: 'Dr. Kavita Rao',
        credits: 4,
        internal: 35,
        external: 0,
        total: 35,
        grade: '-',
        attendancePercent: 92,
        syllabusPercent: 68,
        topics: [
          { name: 'HTML & CSS', completed: true },
          { name: 'JavaScript Basics', completed: true },
          { name: 'DOM Manipulation', completed: true },
          { name: 'React Fundamentals', completed: false },
          { name: 'Node.js & Express', completed: false },
        ],
      },
      {
        id: 'y2s1-5',
        name: 'Discrete Mathematics',
        code: 'BCA305',
        instructor: 'Prof. Rakesh Mehta',
        credits: 3,
        internal: 26,
        external: 0,
        total: 26,
        grade: '-',
        attendancePercent: 80,
        syllabusPercent: 55,
        topics: [
          { name: 'Set Theory', completed: true },
          { name: 'Relations & Functions', completed: true },
          { name: 'Graph Theory', completed: false },
          { name: 'Combinatorics', completed: false },
          { name: 'Mathematical Logic', completed: false },
        ],
      },
      {
        id: 'y2s1-6',
        name: 'Software Engineering',
        code: 'BCA306',
        instructor: 'Dr. Suresh Patil',
        credits: 3,
        internal: 33,
        external: 0,
        total: 33,
        grade: '-',
        attendancePercent: 86,
        syllabusPercent: 62,
        topics: [
          { name: 'SDLC Models', completed: true },
          { name: 'Requirements Engineering', completed: true },
          { name: 'System Design', completed: true },
          { name: 'Testing & QA', completed: false },
          { name: 'Project Management', completed: false },
        ],
      },
    ],
  },
];

export async function getStudentProfile(): Promise<StudentProfile> {
  await new Promise((r) => setTimeout(r, 200));
  return STUDENT_PROFILE;
}

export async function getSemesters(): Promise<Semester[]> {
  await new Promise((r) => setTimeout(r, 300));
  return SEMESTERS;
}
